# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
file_location = "../WeatherPy/Output/weather_data.csv"

weather_df = pd.read_csv(file_location)
weather_df.drop(weather_df.columns[[0]], axis = 1, inplace = True)
weather_df.head()

,City,Country,Temp,Humidity,Lat,Long,Cloud,Wind,Date
0,Hilo,US,78.78,54,19.73,-155.09,40,11.41,1592007263
1,Yellowknife,CA,64.90,55,62.46,-114.35,40,11.41,1592007250
2,Lompoc,US,67.19,49,34.64,-120.46,0,14.99,1592007263
3,San Vicente,AR,66.61,82,-26.62,-54.13,0,4.56,1592007264
4,Lebu,CL,47.44,74,-37.62,-73.65,3,3.49,1592007264

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

In [4]:
coords = weather_df[["Lat", "Long"]]
humidity = weather_df["Humidity"]

fig = gmaps.figure()

heatLayer = gmaps.heatmap_layer(coords,weights=humidity)
fig.add_layer(heatLayer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:

hotel_df = weather_df[(weather_df["Temp"] > 70) & (weather_df["Temp"] < 80) & 
                             (weather_df["Wind"] < 10) & (weather_df["Cloud"] == 0)]
hotel_df = hotel_df.dropna()
hotel_df

,City,Country,Temp,Humidity,Lat,Long,Cloud,Wind,Date
110,Kutum,SD,71.42,26,14.20,24.67,0,1.21,1592007306
135,Faya,SA,70.70,35,18.39,42.45,0,3.91,1592007330
154,Kumul,CN,73.15,19,42.80,93.45,0,3.58,1592007331
178,Dawlatabad,AF,73.06,21,36.41,64.91,0,3.15,1592007346
196,Damietta,EG,77.00,65,31.42,31.81,0,5.82,1592007361
201,Kaka,TM,79.88,17,37.35,59.61,0,7.49,1592007362
211,Zhanakorgan,KZ,73.71,21,43.91,67.25,0,5.01,1592007373
234,Baghdad,IQ,75.20,31,33.34,44.40,0,4.70,1592007356
275,Khuzdar,PK,76.12,16,27.74,66.64,0,4.70,1592007199
344,Nushki,PK,73.65,17,29.55,66.02,0,6.04,1592007390
385,Prado,BR,73.44,86,-17.34,-39.22,0,5.95,1592007394
418,Seydi,TM,79.88,17,39.48,62.91,0,5.91,1592007398
429,Daşoguz,TM,73.40,46,41.84,59.97,0,6.93,1592007399
478,Caravelas,BR,72.27,90,-17.71,-39.25,0,4.68,1592007404
482,Murgab,TM,71.60,46,37.50,61.97,0,5.41,1592007404
510,La Santisima Trinidad,BO,75.43,77,-14.83,-64.90,0,3.76,1592007407
514,Dārāb,IR,76.35,21,28.75,54.54,0,2.21,1592007407
576,Maţāy,EG,79.07,25,28.42,30.78,0,2.84,1592007414

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [44]:
hotel_df["Hotel Name"] = ''
targetRadius = 5000
targetSearch = "Hotel"
targetType = "lodging"

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for index, row in hotel_df.iterrows():
    params = {
    "location": f'{row["Lat"]}, {row["Long"]}',
    "keyword": targetSearch,
    "type": targetType,
    "radius": targetRadius, 
    "key": g_key
    }
    
    response = requests.get(base_url, params).json()
    
    try: 
        hotelName = response['results'][0]['name']
        hotel_df.loc[index, 'Hotel Name'] = hotelName
        print(hotelName)
        locations = hotel_df[["Lat", "Long"]]
        markers = gmaps.marker_layer(locations)
    except (KeyError, IndexError):
        print("No Hotel Found")
    
hotel_df

No Hotel Found
No Hotel Found
Back Hotel
No Hotel Found
فندق المنشي دمياط
No Hotel Found
ARON
Baghdad Hotel
No Hotel Found
ilman Yousafzai
Cahy Praia Hotel
No Hotel Found
Hotel Şabat
Pousada Liberdade
No Hotel Found
Hotel Río Ibare
Naghshe shapoor Hotel
No Hotel Found

AttributeError: 'Figure' object has no attribute 'add_layer_markers'

In [49]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Long"]]

In [54]:
# Add marker layer ontop of heat map
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))